# Практическое задание №5

### 5.1.

Вектор – это частный случай матрицы 1хN и Nх1. Повторите материал для векторов, уделяя особое
внимание умножению A·B.
Вычислите, по возможности не используя программирование: (5E) −1 где Е – единичная матрица
размера 5х5.

In [37]:
import numpy as np
import scipy.linalg

In [3]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 0, -1, 12], float)
print(a)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9.  0. -1. 12.]


In [6]:
print(a[1])

2.0


In [7]:
print(a.shape)

(12,)


In [8]:
b = a * 2
print(b)

[ 2.  4.  6.  8. 10. 12. 14. 16. 18.  0. -2. 24.]


In [9]:
c = a + 1
print(c)

[ 2.  3.  4.  5.  6.  7.  8.  9. 10.  1.  0. 13.]


In [10]:
d = c + b
print(d)

[ 4.  7. 10. 13. 16. 19. 22. 25. 28.  1. -2. 37.]


In [11]:
d = np.subtract(b, c)
print(d)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8. -1. -2. 11.]


In [12]:
print(b - c)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8. -1. -2. 11.]


In [15]:
f = d.transpose()
print(d)
print(d.shape)

print("")
print(f)
print(f.shape)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8. -1. -2. 11.]
(12,)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8. -1. -2. 11.]
(12,)


In [16]:
g = np.dot(f, d)
print(g)
d.shape, f.shape

330.0


((12,), (12,))

### 5.5
Вычислите смешанное произведение трех векторов:
(1, 5, 0), (2, 8, 7) и (7, 1.5, 3)

In [22]:
a = np.array([1, 5, 0], float)
b = np.array([2, 8, 7], float)
c = np.array([7, 1.5, 3], float)
v = np.cross(a, b)
print (np.inner(v, c))
w = np.cross(b, c)
print (np.inner(w, a))

228.5
228.5


# Практическое задание №6

### 1. Решите линейную систему:

In [23]:
A = np.array([[1, 2, 3], [4, 0, 6], [7, 8, 9]])
B = np.array([12, 2, 1])
np.linalg.solve(A, B)

array([-9.2       ,  0.9       ,  6.46666667])

### 2. Найдите псевдорешение:
x + 2y – z = 1

3x – 4y = 7

8x – 5y + 2z = 12

2x – 5z = 7

11x +4y – 7z = 15

In [24]:
A = np.array([[1, 2, -1], [3, -4, 0], [8, -5, 2], [2, 0, -5], [11, 4, -7]])
B = np.array([1, 7, 12, 7, 15])
np.linalg.lstsq(A, B)

<ipython-input-24-8bb72b0258ba>:3: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  np.linalg.lstsq(A, B)


(array([ 1.13919353, -0.90498444, -0.9009803 ]),
 array([0.71523211]),
 3,
 array([15.2817306 ,  9.59852942,  3.65197794]))

### 3. Сколько решений имеет линейная система:

In [30]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = np.array([[12, 2, 1]])
C = np.concatenate((A, B.T), axis=1)
print(C)
np.linalg.matrix_rank(A, 0.0001), np.linalg.matrix_rank(C, 0.0001)

[[ 1  2  3 12]
 [ 4  5  6  2]
 [ 7  8  9  1]]


(2, 3)

Данная система не имеет решений. Заменим последний столбец на [12, 15, 18].

In [31]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = np.array([[12, 15, 18]])
C = np.concatenate((A, B.T), axis=1)
print(C)
np.linalg.matrix_rank(A, 0.0001), np.linalg.matrix_rank(C, 0.0001)

[[ 1  2  3 12]
 [ 4  5  6 15]
 [ 7  8  9 18]]


(2, 2)

Такая система имеет бесконечное количество решений.

### 4. Вычислите LU-разложение матрицы :

In [44]:
A = np.array([ [1, 2, 3], [2, 16, 21], [4, 28, 73]])
P, L, U = scipy.linalg.lu(A)

print(P)
print(L)
print(U)

print(np.dot(P.transpose(), A) - np.dot(L, U))

B = np.array([[4, 1, 7]])
C = np.concatenate((A, B.T), axis=1)
print(C)
print("Ranks: ")
print(f"{np.linalg.matrix_rank(A, 0.0001)}, {np.linalg.matrix_rank(C, 0.0001)}")
print("Result: ")
np.linalg.solve(A, B.T)

[[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]
[[ 1.    0.    0.  ]
 [ 0.25  1.    0.  ]
 [ 0.5  -0.4   1.  ]]
[[  4.    28.    73.  ]
 [  0.    -5.   -15.25]
 [  0.     0.   -21.6 ]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[ 1  2  3  4]
 [ 2 16 21  1]
 [ 4 28 73  7]]
Ranks: 
3, 3
Result: 


array([[ 5.12962963],
       [-0.67592593],
       [ 0.07407407]])